Add groupadd to README and explanation of direct ethernet connection
peachcloud/peach-config pull request #11
Opened 2020-12-19 23:27 UTC by mhfowler

The wpatrl-user group must be created before the user can connect to the internet, which is required for the peach-config script to run, 
so this PR adds the creation of this group for the preinternet setup documentation in the readme. 

I also added an additional section explaining how to optionally configure the pi and the laptop to communicate through ethernet directly. I imagine there might be other or easier ways to do this (and I would be curious to hear them), but the settings listed here are working.

2021-01-07 14:34 UTC, mhfowler commented
@mycognosist I've been keeping PRs open until you approve them before merging. I can also use github to request a review when I'm looking for approval to merge if that makes sense?

2021-01-08 09:03 UTC, mycognosist requested changes
This looks great @mhfowler. Thanks for adding the direct ethernet instructions.

Please bump the version number according to the latest `main` branch number for `peach-config` and fix a small typo on line 142 (traffice -> traffic). Then you're welcome to merge 🙏🏻

2021-01-11 12:53 UTC, mhfowler commented
@mycognosist I bumped the version number to 0.2.3 -- is that what you meant?

2021-01-11 12:55 UTC, mycognosist commented
@mhfowler 

> I bumped the version number to 0.2.3 -- is that what you meant?

Yup, that's perfect. Thanks!

2021-01-11 12:59 UTC, merged